basePath: /api/v1
definitions:
  controller._ResponsePostList:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 响应数据
        items:
          $ref: '#/definitions/models.ApiPostDetail'
        type: array
      msg:
        description: 描述信息
        type: string
    type: object
  models.ApiPostDetail:
    properties:
      author_id:
        description: 作者id
        example: "0"
        type: string
      author_name:
        description: 用户名称
        type: string
      community_id:
        description: 社区ID
        type: integer
      content:
        description: 内容
        type: string
      create_time:
        description: 创建时间
        type: string
      createTime:
        description: 创建时间
        type: string
      id:
        description: 社区id
        type: integer
      introduction:
        description: 介绍
        type: string
      name:
        description: 社区名称
        type: string
      status:
        description: 状态
        type: integer
      title:
        description: 标题
        type: string
      vote_num:
        description: 投票数量
        type: integer
    required:
    - community_id
    - content
    - title
    type: object
host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: 星辰
    url: http://www.swagger.io/support
  description: 文档的各种接口信息
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: bells-of-ireland项目接口文档
  version: "1.0"
paths:
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 社区id
        in: query
        name: community_id
        type: integer
      - description: 排序方式  time:按时间;score:按投票分数
        example: score
        in: query
        name: order
        type: string
      - description: 当前页
        example: 1
        in: query
        name: page
        type: integer
      - description: 每页记录数
        example: 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
swagger: "2.0"
